name: "Pull Request Review"
on:
  pull_request:
    branches:
      - 'develop'
      - 'master'

permissions:
  contents: read
  issues: read
  statuses: write
  pull-requests: write
jobs:
  review:
    runs-on: macos-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ secrets.GH_ACCESS_TOKEN }}
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup swiftlint
        run: |
          if !(type swiftlint); then
            echo 'swiftlint command is not installed.'
            brew install swiftlint
          fi
      - name: Setup danger
        run: gem install danger danger-swiftlint fastlane
      - name: Git fetch
        run: git fetch -t
      - name: Run danger
        run: danger
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
