name: "Get Ready for Release"
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository != 'plaidev/karte-ios-sdk'
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
    - name: Checkout develop
      uses: actions/checkout@v4
      with:
        ref: develop
    - name: Configure Git
      run: |
        git config user.email "git@users.noreply.github.com"
        git config user.name "github actions"
        git fetch
    - name: Get current date
      id: date
      run: echo "DATE=$(date +'%Y.%m.%dT%H.%M.%S')" >> $GITHUB_OUTPUT
    - name: Find Release Targets
      id: find-release-targets
      run: |
        PODSPECS=`git diff remotes/origin/master --name-only | grep podspec`
        for PODSPEC in ${PODSPECS[@]}; do
            RELEASE_TARGETS+="${PODSPEC%.*}, "
        done
        echo "TARGETS=${RELEASE_TARGETS}" >> $GITHUB_OUTPUT
    - name: Create release branch
      run: |
        git checkout -b release/${{ steps.date.outputs.DATE }}
    - name: Update CHANGELOG.md
      run: |
        sed -i "0,/# Releases - xxxx.xx.xx/ s/# Releases - xxxx.xx.xx/# Releases - $(date '+%Y.%m.%d')\n## Version $(cat .spm-version)/g" ./CHANGELOG.md
        git add ./CHANGELOG.md
        git commit -m "Update CHANGELOG.md"
    - name: Push release branch
      run: git push origin -u release/${{ steps.date.outputs.date }}
    - name: Pull Request Action
      uses: vsoch/pull-request-action@1.1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        PULL_REQUEST_BRANCH: master
        PULL_REQUEST_FROM_BRANCH: release/${{ steps.date.outputs.date }}
        PULL_REQUEST_TITLE: Deploy to production by ${{ github.actor }}
        PULL_REQUEST_BODY: |
          ### 以下の項目を確認してください
          - [ ] Podspecのバージョンが正しく更新されていること
          - [ ] 配信されたサンプルアプリでの動作確認
          - [ ] spm-versionが更新されていること 
          - [ ] CHANGELOG.md のリリース日付が正しく設定されていること
          - [ ] CHANGELOG.md のバージョンがPodspecのバージョンと一致していること
          - [ ] 全てのチェックボックスを埋めると自動的にマージ作業を開始します

          ### Update
          ${{ steps.find-release-targets.outputs.TARGETS }}
    - name: Request beta release
      uses: actions/github-script@v7
      with:
        github-token: ${{ secrets.SHARED_GITHUB_ACCESS_TOKEN }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'plaidev',
            repo: '${{vars.UITEST_REPO}}',
            workflow_id: 'release-test-app.yml',
            ref: 'master',
            inputs: {
              sdkBranch: 'release/${{ steps.date.outputs.date }}',
            },
          })
